name: Check PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  check_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Check lint and markdown links'
        run: |
          yarn check-markdown-link
          yarn lint
        shell: bash
      - name: 'Setup Firestore Emulator'
        run: |
          cd scripts
          yarn run firebase setup:emulators:firestore
        shell: bash
      - name: 'Run unit tests'
        run: |
          cp scripts/.firebaserc scripts/firebase.json .
          echo 'yarn test-without-starting-db' > ./test.sh
          chmod u+x ./test.sh
          yarn run firebase emulators:exec --only firestore ./test.sh
        shell: bash
